services:
  nextjs:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
