services:
  web:
    build: .
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
        - action: sync
          path: .
          target: /app
